apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 2
  selector:
      app: myjenkins
  template:
    metadata:
      labels:
        app: myjenkins
    spec:
      containers:
        - name: myjenkins-container
          image: jenkins:2.60.3
          ports:
            - containerPort: 8080